name: Release
on: 
  release:
    types: [created]
    tags:
      - 'v*.*.*'
    

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup dotnet version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-restore --no-build
  publish:
    name: Push project on Nuget
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    - name: GET Version
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:11}
    - name: Setup dotnet version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Pack
      run: dotnet pack ./src/Mozilla.IoT.WebThing -c Release --include-source -o ./artifacts/pack -p:PackageVersion=${{env.RELEASE_VERSION}}
    - name: Publish to Nuget
      run: dotnet nuget push ./artifacts/pack/*.nupkg -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json
